let caterpillarX=400,caterpillarY=300,velocityX=0,velocityY=0;
const bodySegments=9,numberOfFlowers=12,numberOfGrass=180,speed=6;
let bodyX=[],bodyY=[],flowerX=[],flowerY=[],grassX=[],grassY=[];
function setup(){const canvas=createCanvas(1000,700);canvas.parent("canvas-host");for(let i=0;i<bodySegments;i++){bodyX[i]=caterpillarX-i*32;bodyY[i]=caterpillarY;}randomSeed(10);for(let i=0;i<numberOfFlowers;i++){flowerX[i]=random(80,width-80);flowerY[i]=random(80,height-80);if(dist(flowerX[i],flowerY[i],caterpillarX,caterpillarY)<180){flowerX[i]+=180;flowerY[i]+=100;}}for(let i=0;i<numberOfGrass;i++){grassX[i]=random(width);grassY[i]=random(height);}}
function draw(){background(115,175,90);drawGrass();for(let i=0;i<numberOfFlowers;i++)drawFlower(flowerX[i],flowerY[i]);readKeyboard();moveCaterpillar();updateBody();drawCaterpillar();}
function readKeyboard(){velocityX=(keyIsDown(RIGHT_ARROW)?speed:0)-(keyIsDown(LEFT_ARROW)?speed:0);velocityY=(keyIsDown(DOWN_ARROW)?speed:0)-(keyIsDown(UP_ARROW)?speed:0);if(velocityX&&velocityY){velocityX*=.707;velocityY*=.707;}}
function drawGrass(){stroke(70,140,65);strokeWeight(2);for(let i=0;i<numberOfGrass;i++){line(grassX[i],grassY[i],grassX[i]-3,grassY[i]-8);line(grassX[i],grassY[i],grassX[i]+3,grassY[i]-7);}noStroke();}
function drawFlower(x,y){stroke(45,125,55);strokeWeight(4);line(x,y+5,x,y+35);fill(55,145,65);ellipse(x-8,y+22,16,8);ellipse(x+8,y+27,16,8);noStroke();fill(255,105,165);circle(x-12,y,22);circle(x+12,y,22);circle(x,y-12,22);circle(x,y+12,22);fill(255,205,60);circle(x,y,17);}
function moveCaterpillar(){let newX=caterpillarX+velocityX,newY=caterpillarY+velocityY,blocked=false;for(let i=0;i<numberOfFlowers;i++){if(dist(newX,newY,flowerX[i],flowerY[i])<65){blocked=true;const angle=atan2(newY-flowerY[i],newX-flowerX[i]);newX+=cos(angle)*3;newY+=sin(angle)*3;}}if(!blocked){caterpillarX=newX;caterpillarY=newY;}caterpillarX=constrain(caterpillarX,35,width-35);caterpillarY=constrain(caterpillarY,35,height-35);}
function updateBody(){for(let i=bodySegments-1;i>0;i--){bodyX[i]=lerp(bodyX[i],bodyX[i-1],.25);bodyY[i]=lerp(bodyY[i],bodyY[i-1],.25);}bodyX[0]=lerp(bodyX[0],caterpillarX,.35);bodyY[0]=lerp(bodyY[0],caterpillarY,.35);}
function drawCaterpillar(){for(let i=bodySegments-1;i>=0;i--){const size=i===0?58:43;fill(245,205,35);noStroke();circle(bodyX[i],bodyY[i],size);noFill();stroke(220,165,20);strokeWeight(2);circle(bodyX[i],bodyY[i],size);}const hx=bodyX[0],hy=bodyY[0];noStroke();fill(255);ellipse(hx-12,hy-9,15,18);ellipse(hx+12,hy-9,15,18);fill(30);ellipse(hx-12,hy-8,6,8);ellipse(hx+12,hy-8,6,8);noFill();stroke(80,50,20);strokeWeight(2);arc(hx,hy+4,20,15,0,PI);line(hx-12,hy-25,hx-20,hy-40);line(hx+12,hy-25,hx+20,hy-40);fill(255,105,165);circle(hx-20,hy-40,8);circle(hx+20,hy-40,8);noStroke();}
function keyPressed(){if([LEFT_ARROW,RIGHT_ARROW,UP_ARROW,DOWN_ARROW].includes(keyCode))return false;}function keyReleased(){if([LEFT_ARROW,RIGHT_ARROW,UP_ARROW,DOWN_ARROW].includes(keyCode))return false;}
