let keys={},px,py,angle=0,lives=3,inv=0,weapon="Knife",xp=0,floorNo=1,won=false,msg="",msgTime=0;
let unlocked={Pistol:false,"Assault Rifle":false,Sniper:false},ammo={Pistol:0,"Assault Rifle":0,Sniper:0};
let walls=[],enemies=[],shots=[],enemyShots=[],loot=[],hostage,exitDoor,hostageSaved=false,exitOpen=false,cooldown=0,flash=0;
const RX=50,RY=50,RW=700,RH=500,MAX=20;
function setup(){createCanvas(800,600).parent("canvas-host");loadFloor(1)}
function draw(){background(30);if(won)return endScreen();stroke(200);strokeWeight(4);noFill();rect(RX,RY,RW,RH);walls.forEach(w=>w.draw());movePlayer();enemies.forEach(e=>e.update());updateShots();updateEnemyShots();if(inv>0)inv--;if(cooldown>0)cooldown--;if(msgTime>0)msgTime--;walls.forEach(()=>{});if(!hostageSaved)drawPerson(hostage.x,hostage.y,0,color(255,150,30),null,1);loot.forEach(l=>l.draw());exitOpen=enemies.every(e=>!e.alive)&&hostageSaved;drawExit();enemies.forEach(e=>e.draw());shots.forEach(s=>s.draw());enemyShots.forEach(s=>s.draw());if(!inv||frameCount%6<3)drawPerson(px,py,angle,color(0,140,255),weapon,keys.c?.85:1);drawFlash();if(exitOpen&&dist(px,py,exitDoor.x,exitDoor.y)<28){lives=min(3,lives+1);loadFloor(floorNo+1)}hud();if(lives<=0)gameOver()}
function movePlayer(){if(lives<=0)return;let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0);if(!dx&&!dy)return;let n=sqrt(dx*dx+dy*dy),sp=keys.c?1.5:3,nx=constrain(px+dx/n*sp,RX+15,RX+RW-15),ny=constrain(py+dy/n*sp,RY+15,RY+RH-15);if(!wallHit(nx,py,14))px=nx;if(!wallHit(px,ny,14))py=ny;angle=atan2(dy,dx)}
const wallHit=(x,y,r)=>walls.some(w=>x>w.x-r&&x<w.x+w.w+r&&y>w.y-r&&y<w.y+w.h+r);
function act(){if(lives<=0||won)return;if(weapon==="Knife"){for(const e of enemies)if(e.alive&&dist(px,py,e.x,e.y)<40){let silent=!e.alert,died=e.hit();if(died){xp+=silent?25:10;drop(e);unlock();say(silent?"Silent kill! +25 XP":"Kill! +10 XP")}else say(e.boss?`Boss lives: ${e.bossLives}`:`Hit! ${e.hp} HP left`);return}}else if(cooldown===0){if(ammo[weapon]>0){shots.push(new Shot(px,py,angle,weapon,false));ammo[weapon]--;cooldown=weapon==="Assault Rifle"?6:weapon==="Sniper"?45:20;flash=6;let radius=weapon==="Pistol"?130:weapon==="Sniper"?400:9999;enemies.forEach(e=>{if(dist(px,py,e.x,e.y)<radius)e.forced=true})}else say("Out of ammo! Loot enemies to restock")}if(!hostageSaved&&dist(px,py,hostage.x,hostage.y)<40){hostageSaved=true;say("Hostage rescued!");return}for(const l of loot)if(!l.taken&&dist(px,py,l.x,l.y)<30){l.taken=true;if(l.type==="XP"){xp+=l.n;unlock();say(`+${l.n} XP`)}else if(l.type==="Health"){lives=min(3,lives+1);say("+1 Life")}else{ammo[l.type]+=l.n;say(`+${l.n} ${l.type} ammo`)}return}}
function unlock(){if(xp>=50&&!unlocked.Pistol){unlocked.Pistol=true;ammo.Pistol=12;say("Pistol unlocked — press 2")}if(xp>=150&&!unlocked["Assault Rifle"]){unlocked["Assault Rifle"]=true;ammo["Assault Rifle"]=30;say("Assault Rifle unlocked — press 3")}if(xp>=300&&!unlocked.Sniper){unlocked.Sniper=true;ammo.Sniper=5;say("Sniper unlocked — press 4")}}
function say(s){msg=s;msgTime=120}
function drop(e){if(e.boss)loot.push(new Loot(e.x-10,e.y,"XP",80),new Loot(e.x+10,e.y,"Health",1),new Loot(e.x,e.y+15,"Assault Rifle",20));else{let r=random();if(r<.5)loot.push(new Loot(e.x,e.y,"XP",floor(random(10,25))));else if(r<.85){let type=random(["Pistol","Assault Rifle","Sniper"]);loot.push(new Loot(e.x,e.y,type,type==="Pistol"?6:type==="Assault Rifle"?15:2))}else loot.push(new Loot(e.x,e.y,"Health",1))}}
function updateShots(){for(let i=shots.length-1;i>=0;i--){let b=shots[i];b.update();let removed=false;for(const e of enemies)if(e.alive&&dist(b.x,b.y,e.x,e.y)<18){let died=e.hit();if(died){xp+=b.type==="Sniper"?30:b.type==="Pistol"?15:10;unlock();drop(e)}else if(e.boss)say(`Boss lives: ${e.bossLives}`);shots.splice(i,1);removed=true;break}if(!removed&&out(b)){shots.splice(i,1)}}}
function updateEnemyShots(){for(let i=enemyShots.length-1;i>=0;i--){let b=enemyShots[i];b.update();if(out(b)){enemyShots.splice(i,1);continue}if(!inv&&dist(b.x,b.y,px,py)<16){lives--;inv=60;enemyShots.splice(i,1)}}}
const out=b=>wallHit(b.x,b.y,2)||b.x<RX||b.x>RX+RW||b.y<RY||b.y>RY+RH;
function loadFloor(n){if(n>MAX){won=true;return}floorNo=n;walls=[];enemies=[];shots=[];enemyShots=[];loot=[];hostageSaved=false;inv=0;say(`Floor ${n}${n%5===0?" — BOSS FLOOR":""}`);n%5===0?bossFloor(n):regularFloor(n)}
function tier(n){return n<=3?"Knife":n<=7?"Pistol":n<=13?"Assault Rifle":"Sniper"}
function regularFloor(n){let odd=n%2===1,slots;if(odd){px=150;py=120;walls.push(new Wall(345,50,10,200),new Wall(345,330,10,220),new Wall(350,295,200,10),new Wall(630,295,120,10));slots=[[150,450,300,450],[120,300,300,300],[420,100,700,100],[420,180,650,180],[420,450,700,450]]}else{px=120;py=100;walls.push(new Wall(50,295,200,10),new Wall(330,295,420,10),new Wall(395,300,10,80),new Wall(395,460,10,90));slots=[[300,100,550,100],[150,220,400,220],[100,400,100,520],[250,380,250,520],[500,380,700,520]]}let count=constrain(3+floor(n/6),3,5),sp=constrain(1.2+n*.03,1.2,2.6),det=constrain(140+n*4,140,300);for(let i=0;i<count;i++){let s=slots[i],dog=!odd&&i===4;enemies.push(new Enemy(s[0],s[1],s[2],s[3],dog?sp*1.3:sp,dog?det*.85:det,dog?"Knife":tier(n),false,1,0))}hostage={x:650,y:470};exitDoor={x:720,y:520}}
function bossFloor(n){px=150;py=300;walls.push(new Wall(395,50,10,200),new Wall(395,350,10,200));let sp=constrain(1.2+n*.03,1.2,2.6),det=constrain(140+n*4,140,300),gt=tier(max(1,n-3));enemies.push(new Enemy(150,150,300,150,sp,det,gt,false,1,0),new Enemy(150,450,300,450,sp,det,gt,false,1,0));let data=n===20?["Gatling",3,6,2.2,300,1.4]:n===15?["Sniper",2,5,1.8,260,1.3]:n===10?["Assault Rifle",2,4,1.7,240,1.2]:["Pistol",2,3,1.6,220,1.1];let e=new Enemy(650,300,650,300,data[5],data[4],data[0],true,data[2],data[1]);e.scale=data[3];enemies.push(e);hostage={x:650,y:150};exitDoor={x:720,y:520}}
function drawPerson(x,y,a,body,held,sc=1){push();translate(x,y);rotate(a);scale(sc);stroke(20);strokeWeight(3);line(-4,8,-7,17);line(4,8,7,17);noStroke();fill(body);rectMode(CENTER);rect(0,0,15,17,3);stroke(body);strokeWeight(4);line(-7,-3,-13,3);line(7,-3,15,-3);noStroke();fill(held?color(255,210,160):color(255,210,160));ellipse(0,-15,15);if(held){stroke(held==="Knife"?235:150);strokeWeight(held==="Knife"?3:5);line(10,-3,held==="Sniper"?32:held==="Knife"?22:28,held==="Knife"?-9:-3)}pop()}
function drawExit(){push();translate(exitDoor.x,exitDoor.y);fill(exitOpen?color(0,255,120):90);stroke(exitOpen?color(0,255,120):140);strokeWeight(3);rectMode(CENTER);rect(0,0,36,50,4);pop()}
function drawFlash(){if(flash<=0)return;noStroke();fill(255,230,130,map(flash,0,6,0,255));ellipse(px+cos(angle)*22,py+sin(angle)*22,14);flash--}
function hud(){fill(255);textSize(15);text(`Floor: ${floorNo} / ${MAX}`,20,20);text(`Lives: ${lives}`,20,40);text(`Weapon: ${weapon}${weapon==="Knife"?"":` Ammo: ${ammo[weapon]}`}`,20,60);let next=!unlocked.Pistol?50:!unlocked["Assault Rifle"]?150:!unlocked.Sniper?300:-1;text(`XP: ${xp}${next>0?` / ${next} to next unlock`:" (all unlocked)"}`,20,80);text(`Enemies remaining: ${enemies.filter(e=>e.alive).length}`,20,105);text(`Hostage: ${hostageSaved?"Rescued":"Not rescued"}`,20,125);text(exitOpen?"EXIT UNLOCKED — reach the green door":"Exit locked until floor is clear",20,145);if(keys.c)text("Crouching — harder to spot, slower",20,165);textSize(12);text("Move: WASD | Crouch: C | Attack/Interact/Loot: SPACE | Switch weapon: 1–4",20,height-15);if(msgTime){fill(255,255,0);textAlign(CENTER,TOP);textSize(18);text(msg,width/2,20);textAlign(LEFT,BASELINE)}}
function gameOver(){fill(0,200);rect(0,0,width,height);fill(255,60,60);textAlign(CENTER,CENTER);textSize(40);text("GAME OVER",width/2,height/2-20);fill(255);textSize(16);text("Press R to restart",width/2,height/2+20);textAlign(LEFT,BASELINE)}
function endScreen(){background(30);fill(255);textAlign(CENTER,CENTER);textSize(30);text("MISSION COMPLETE",width/2,height/2-30);textSize(16);text("You defeated the final boss and cleared all 20 floors.",width/2,height/2+5);text(`Final XP: ${xp} — press R to restart`,width/2,height/2+30)}
function restart(){keys={};lives=3;xp=0;weapon="Knife";unlocked={Pistol:false,"Assault Rifle":false,Sniper:false};ammo={Pistol:0,"Assault Rifle":0,Sniper:0};won=false;loadFloor(1)}
function keyPressed(){let k=key.toLowerCase();if("wasdc".includes(k))keys[k]=true;if(key===' ')act();if(key==='1')weapon="Knife";if(key==='2'&&unlocked.Pistol)weapon="Pistol";if(key==='3'&&unlocked["Assault Rifle"])weapon="Assault Rifle";if(key==='4'&&unlocked.Sniper)weapon="Sniper";if(k==='r'&&(lives<=0||won))restart();if(k==='n'&&!won&&lives>0)loadFloor(floorNo+1);return false}
function keyReleased(){let k=key.toLowerCase();if("wasdc".includes(k))keys[k]=false;return false}
class Wall{constructor(x,y,w,h){Object.assign(this,{x,y,w,h})}draw(){fill(90);noStroke();rect(this.x,this.y,this.w,this.h)}}
class Loot{constructor(x,y,type,n){Object.assign(this,{x,y,type,n});this.taken=false}draw(){if(this.taken)return;push();translate(this.x,this.y);noStroke();if(this.type==="XP"){fill(255,220,0);quad(0,-8,8,0,0,8,-8,0)}else if(this.type==="Health"){fill(255,60,60);rectMode(CENTER);rect(0,0,4,16);rect(0,0,16,4)}else{fill(120,200,255);rectMode(CENTER);rect(0,0,14,8,2)}pop()}}
class Shot{constructor(x,y,a,type,enemy){Object.assign(this,{x,y,a,type,enemy});this.speed=type==="Sniper"?(enemy?18:20):type==="Assault Rifle"?enemy?8:10:type==="Gatling"?9:enemy?7:8}update(){this.x+=cos(this.a)*this.speed;this.y+=sin(this.a)*this.speed}draw(){fill(this.enemy?color(255,60,60):color(255,255,0));noStroke();ellipse(this.x,this.y,this.type==="Sniper"?8:5)}}
class Enemy{constructor(x,y,bx,by,speed,detect,weapon,boss,hp,bossLives){Object.assign(this,{x,y,ax:x,ay:y,bx,by,speed,detect,weapon,boss,hp,bossLives});this.hpLife=hp;this.scale=1;this.toB=true;this.alive=true;this.alert=false;this.forced=false;this.face=0;this.shoot=0;this.death=0}hit(){if(--this.hp>0)return false;if(this.boss&&this.bossLives>1){this.bossLives--;this.hp=this.hpLife;return false}this.alive=false;this.death=20;return true}see(){let d=dist(this.x,this.y,px,py),r=this.detect*(keys.c?.5:1);if(d>r)return false;if(d<28)return true;let diff=atan2(py-this.y,px-this.x)-this.face;while(diff>PI)diff-=TWO_PI;while(diff<-PI)diff+=TWO_PI;return abs(diff)<radians(55)}update(){if(!this.alive){if(this.death>0)this.death--;return}if(lives<=0)return;this.alert=this.forced||this.see();let tx=this.alert?px:this.toB?this.bx:this.ax,ty=this.alert?py:this.toB?this.by:this.ay;if(!this.alert&&dist(this.x,this.y,tx,ty)<5)this.toB=!this.toB;let dx=tx-this.x,dy=ty-this.y,n=sqrt(dx*dx+dy*dy);if(n>.001){this.face=atan2(dy,dx);let nx=this.x+dx/n*this.speed,ny=this.y+dy/n*this.speed;if(!wallHit(nx,this.y,12))this.x=nx;if(!wallHit(this.x,ny,12))this.y=ny}if(!inv&&dist(this.x,this.y,px,py)<24){lives--;inv=60}if(this.alert&&this.weapon!=="Knife"){if(this.shoot<=0){enemyShots.push(new Shot(this.x,this.y,atan2(py-this.y,px-this.x),this.weapon,true));this.shoot=this.weapon==="Gatling"?8:this.weapon==="Assault Rifle"?20:this.weapon==="Sniper"?75:45}else this.shoot--}}draw(){if(!this.alive&&!this.death)return;if(!this.alive){fill(120,40,40,map(this.death,0,20,0,255));noStroke();ellipse(this.x,this.y,24,12);return}noStroke();fill(255,80,0,this.alert?55:25);arc(this.x,this.y,this.detect*2,this.detect*2,this.face-radians(55),this.face+radians(55),PIE);let body=this.boss?color(140,20,140):this.alert?color(255,80,0):color(190,40,40);drawPerson(this.x,this.y,this.face,body,this.weapon,this.boss?this.scale:1)}}
