let playerX,playerY,velocityX=0,velocityY=0,playing=false,gameOver=false,score=0,survivalTime=0,lastFrameTime,worldRadius,collapse=0,worldRotation=0;
const playerSize=18,ENERGY_COUNT=8,MAX_OBSTACLES=40,PARTICLE_COUNT=180;
let energyX=[],energyY=[],obstacleX=Array(MAX_OBSTACLES),obstacleY=Array(MAX_OBSTACLES),obstacleSize=Array(MAX_OBSTACLES),obstacleActive=Array(MAX_OBSTACLES).fill(false),particleX=[],particleY=[],particleSpeed=[];
function setup(){const canvas=createCanvas(1000,700);canvas.parent("canvas-host");worldRadius=min(width,height)*.4;playerX=width/2;playerY=height/2;createEnergy();createParticles();lastFrameTime=millis();}
function draw(){background(3);if(!playing&&!gameOver){drawTitleScreen();return;}if(gameOver){drawWorld();drawGameOver();return;}updateGame();drawWorld();drawInterface();}
function drawTitleScreen(){textAlign(CENTER,CENTER);fill(255);textSize(70);text("VOID",width/2,height/2-80);textSize(15);fill(150);text("CONTROL THE VOID",width/2,height/2);textSize(13);fill(180);text("PRESS SPACE OR MOVE TO BEGIN",width/2,height/2+45);noFill();stroke(60);strokeWeight(1);circle(width/2,height/2-80,170);noStroke();fill(255);circle(width/2,height/2-80,10);}
function startGame(){playing=true;gameOver=false;score=0;survivalTime=0;collapse=0;worldRotation=0;playerX=width/2;playerY=height/2;velocityX=velocityY=0;obstacleActive.fill(false);createEnergy();createParticles();lastFrameTime=millis();}
function inputVector(){let x=(keyIsDown(RIGHT_ARROW)?1:0)-(keyIsDown(LEFT_ARROW)?1:0),y=(keyIsDown(DOWN_ARROW)?1:0)-(keyIsDown(UP_ARROW)?1:0);if(x&&y){x*=.707;y*=.707;}return{x,y};}
function updateGame(){let now=millis(),dt=constrain((now-lastFrameTime)/1000,0,.05);lastFrameTime=now;survivalTime+=dt;const difficulty=1+survivalTime/12;collapse+=dt*2;const currentRadius=max(worldRadius-collapse,120),input=inputVector(),acceleration=.65;velocityX=(velocityX+input.x*acceleration)*.86;velocityY=(velocityY+input.y*acceleration)*.86;velocityX=constrain(velocityX,-8,8);velocityY=constrain(velocityY,-8,8);playerX+=velocityX;playerY+=velocityY;worldRotation+=input.x*.01;let dx=playerX-width/2,dy=playerY-height/2,d=sqrt(dx*dx+dy*dy);if(d>currentRadius-playerSize/2){const angle=atan2(dy,dx);playerX=width/2+cos(angle)*(currentRadius-playerSize/2);playerY=height/2+sin(angle)*(currentRadius-playerSize/2);velocityX*=-.35;velocityY*=-.35;}for(let i=0;i<ENERGY_COUNT;i++)if(dist(playerX,playerY,energyX[i],energyY[i])<25){score+=10;spawnEnergy(i);}if(random(1)<.008*difficulty)spawnObstacle();for(let i=0;i<MAX_OBSTACLES;i++){if(!obstacleActive[i])continue;let ox=obstacleX[i]-width/2,oy=obstacleY[i]-height/2,od=sqrt(ox*ox+oy*oy);if(od>0){const speed=.35+difficulty*.08;obstacleX[i]+=(ox/od)*speed;obstacleY[i]+=(oy/od)*speed;}if(dist(playerX,playerY,obstacleX[i],obstacleY[i])<playerSize/2+obstacleSize[i]){endGame();return;}if(od<20)obstacleActive[i]=false;}updateParticles();}
function drawWorld(){push();translate(width/2,height/2);rotate(worldRotation);noFill();stroke(30);strokeWeight(1);circle(0,0,worldRadius*2);const radius=max(worldRadius-collapse,120);stroke(100);circle(0,0,radius*2);stroke(15);for(let r=80;r<radius;r+=60)circle(0,0,r*2);drawParticles();for(let i=0;i<ENERGY_COUNT;i++)drawEnergy(energyX[i]-width/2,energyY[i]-height/2);for(let i=0;i<MAX_OBSTACLES;i++)if(obstacleActive[i])drawObstacle(obstacleX[i]-width/2,obstacleY[i]-height/2,obstacleSize[i]);pop();drawPlayer();}
function drawPlayer(){noStroke();for(let i=5;i>=1;i--){fill(255,20);circle(playerX-velocityX*i*1.8,playerY-velocityY*i*1.8,playerSize);}fill(255);circle(playerX,playerY,playerSize);fill(0);circle(playerX,playerY,5);}
function drawEnergy(x,y){push();translate(x,y);rotate(-worldRotation);noFill();stroke(220);strokeWeight(1);circle(0,0,24);line(-6,0,6,0);line(0,-6,0,6);pop();}
function drawObstacle(x,y,size){push();translate(x,y);rotate(-worldRotation*2);rectMode(CENTER);noFill();stroke(120);strokeWeight(2);rect(0,0,size*2,size*2);line(-size,-size,size,size);line(size,-size,-size,size);pop();}
function createParticles(){for(let i=0;i<PARTICLE_COUNT;i++){particleX[i]=random(width);particleY[i]=random(height);particleSpeed[i]=random(.15,.8);}}
function updateParticles(){for(let i=0;i<PARTICLE_COUNT;i++){const dx=width/2-particleX[i],dy=height/2-particleY[i],d=sqrt(dx*dx+dy*dy);if(d>1){particleX[i]+=dx/d*particleSpeed[i];particleY[i]+=dy/d*particleSpeed[i];}if(particleX[i]<0||particleX[i]>width||particleY[i]<0||particleY[i]>height){particleX[i]=random(width);particleY[i]=random(height);}}}
function drawParticles(){noStroke();for(let i=0;i<PARTICLE_COUNT;i++){fill(70);circle(particleX[i]-width/2,particleY[i]-height/2,2);}}
function createEnergy(){for(let i=0;i<ENERGY_COUNT;i++)spawnEnergy(i);}function spawnEnergy(i){const angle=random(TWO_PI),radius=random(100,worldRadius-40);energyX[i]=width/2+cos(angle)*radius;energyY[i]=height/2+sin(angle)*radius;}
function spawnObstacle(){for(let i=0;i<MAX_OBSTACLES;i++)if(!obstacleActive[i]){obstacleActive[i]=true;const angle=random(TWO_PI),radius=worldRadius+30;obstacleX[i]=width/2+cos(angle)*radius;obstacleY[i]=height/2+sin(angle)*radius;obstacleSize[i]=random(8,18);return;}}
function drawInterface(){textAlign(LEFT,TOP);textSize(16);fill(255);text("VOID",25,20);textSize(12);fill(130);text(`ENERGY  ${score}`,25,50);text(`TIME  ${survivalTime.toFixed(1)}`,25,68);text(`SYSTEM LEVEL  ${(1+survivalTime/12).toFixed(1)}`,25,86);if(collapse>worldRadius*.55){textAlign(CENTER,TOP);fill(180);text("THE VOID IS COLLAPSING",width/2,25);}}
function endGame(){gameOver=true;playing=false;}function drawGameOver(){fill(0,210);noStroke();rectMode(CORNER);rect(0,0,width,height);textAlign(CENTER,CENTER);fill(255);textSize(60);text("VOID",width/2,height/2-90);textSize(18);fill(170);text("CONNECTION LOST",width/2,height/2-30);textSize(13);fill(120);text(`ENERGY  ${score}`,width/2,height/2+20);text(`SURVIVED  ${survivalTime.toFixed(1)} SEC`,width/2,height/2+45);fill(255);textSize(12);text("PRESS SPACE TO RESTART",width/2,height/2+100);}
function keyPressed(){if((key===" "||keyCode===ENTER)&&!playing){startGame();return false;}if(key==="r"||key==="R"){startGame();return false;}if(!playing&&!gameOver&&[LEFT_ARROW,RIGHT_ARROW,UP_ARROW,DOWN_ARROW].includes(keyCode)){startGame();return false;}if([LEFT_ARROW,RIGHT_ARROW,UP_ARROW,DOWN_ARROW].includes(keyCode))return false;}function keyReleased(){if([LEFT_ARROW,RIGHT_ARROW,UP_ARROW,DOWN_ARROW].includes(keyCode))return false;}
