let x,y,hardness=0,score=0,lives=3,cols=15,rows=10,cell=40,grid=[],doorX,doorY,lastDoor=0;
let foodX,foodY,powerX=-100,powerY=-100,powerDX=0,powerDY=0,powerActive=false,lastPower=0;
let invincible=false,invTimer=0,recovering=false,recoverTimer=0,poisons=[],wasMoving=false,over=false;
function setup(){createCanvas(600,400).parent('canvas-host');generateLevel()}
function draw(){if(over)return gameOverScreen();background(15,10,20);if(invincible&&millis()-invTimer>5000)invincible=false;if(recovering&&millis()-recoverTimer>2000)recovering=false;let dx=(keyIsDown(RIGHT_ARROW)?5:0)-(keyIsDown(LEFT_ARROW)?5:0),dy=(keyIsDown(DOWN_ARROW)?5:0)-(keyIsDown(UP_ARROW)?5:0),moving=!!(dx||dy);if(!moving&&wasMoving)poisons.push({x,y,time:millis()});wasMoving=moving;let nx=x+dx,ny=y+dy;if(!wallHit(nx,y))x=nx;if(!wallHit(x,ny))y=ny;x=constrain(x,15,width-15);y=constrain(y,15,height-15);drawWalls();spikes();drawPoisons();drawFood();updatePower();if(millis()-lastDoor>3000)teleportDoor();drawDoor();if(dist(x,y,doorX+20,doorY+20)<30){hardness++;score+=50;generateLevel()}fill(invincible?(millis()%200<100?255:color(255,234,3)):recovering?(millis()%200<100?color(255,0,128):color(255,234,3)):color(255,234,3));noStroke();ellipse(x,y,32);hud()}
function drawWalls(){fill(113,71,249,90);noStroke();for(let i=0;i<cols;i++)for(let j=0;j<rows;j++)if(grid[i][j])rect(i*cell+2,j*cell+2,cell-4,cell-4,15)}
function spikes(){fill(255,0,128,160);noStroke();for(let i=0;i<width;i+=15){triangle(i,0,i+15,0,i+7.5,15);triangle(i,height,i+15,height,i+7.5,height-15)}for(let i=0;i<height;i+=15){triangle(0,i,0,i+15,15,i+7.5);triangle(width,i,width,i+15,width-15,i+7.5)}if(!invincible&&!recovering&&(x<31||x>width-31||y<31||y>height-31)){lives--;if(lives<=0)over=true;else{recovering=true;recoverTimer=millis()}}}
function drawPoisons(){for(let i=poisons.length-1;i>=0;i--){let p=poisons[i],age=millis()-p.time;if(age<1500){fill(139,254,0,80);noStroke();ellipse(p.x,p.y,28);ellipse(p.x-10,p.y+6,18);ellipse(p.x+10,p.y-6,16)}else{fill(139,254,0,160);ellipse(p.x,p.y-4,30,28);rect(p.x-8,p.y+2,16,12,4);fill(15,10,20);ellipse(p.x-6,p.y-3,8);ellipse(p.x+6,p.y-3,8);if(dist(x,y,p.x,p.y)<25){if(invincible){poisons.splice(i,1);score+=5}else over=true}}}}
function drawFood(){let cx=foodX+20,cy=foodY+20;fill(0,255,200,200);noStroke();beginShape();vertex(cx,cy-16);quadraticVertex(cx,cy,cx+16,cy);quadraticVertex(cx,cy,cx,cy+16);quadraticVertex(cx,cy,cx-16,cy);quadraticVertex(cx,cy,cx,cy-16);endShape(CLOSE);if(dist(x,y,cx,cy)<25){score+=10;spawnFood()}}
function updatePower(){if(!powerActive&&millis()-lastPower>2500)spawnPower();if(!powerActive)return;let nx=powerX+powerDX,ny=powerY+powerDY;if(wallHit(nx,powerY))powerDX*=-1;else powerX=nx;if(wallHit(powerX,ny))powerDY*=-1;else powerY=ny;if(powerX<15||powerX>width-15)powerDX*=-1;if(powerY<15||powerY>height-15)powerDY*=-1;fill(millis()%400<200?color(255,234,3,200):color(255,0,128,200));noStroke();beginShape();for(let i=0;i<10;i++){let a=TWO_PI/10*i-HALF_PI,r=i%2?6:16;vertex(powerX+r*cos(a),powerY+r*sin(a))}endShape(CLOSE);if(dist(x,y,powerX,powerY)<25){invincible=true;recovering=false;invTimer=millis();powerActive=false;lastPower=millis()}}
function drawDoor(){noFill();strokeWeight(3);stroke(255,234,3,160);ellipse(doorX+20,doorY+20,36);stroke(0,255,200,160);ellipse(doorX+20,doorY+20,18);noStroke()}
function hud(){textAlign(LEFT,BASELINE);textSize(16);fill(255,234,3);text(`Level: ${hardness}`,10,20);text(`Score: ${score}`,10,40);fill(255,0,128);text(`Lives: ${lives}`,10,60)}
function generateLevel(){x=width/2;y=height/2;poisons=[];invincible=recovering=powerActive=false;lastPower=millis();grid=Array.from({length:cols},()=>Array(rows).fill(0));for(let i=0;i<min(10+hardness*4,60);i++){let c=floor(random(cols)),r=floor(random(rows));if(!(c>=6&&c<=8&&r>=4&&r<=5))grid[c][r]=1}teleportDoor();spawnFood()}
function emptyCell(avoid=[]){for(let tries=0;tries<500;tries++){let c=floor(random(cols)),r=floor(random(rows));if(!grid[c][r]&&avoid.every(p=>dist(c*cell,r*cell,p.x,p.y)>10))return{x:c*cell,y:r*cell}}return{x:cell,y:cell}}
function teleportDoor(){let p=emptyCell();doorX=p.x;doorY=p.y;lastDoor=millis()}
function spawnFood(){let p=emptyCell([{x:doorX,y:doorY}]);foodX=p.x;foodY=p.y}
function spawnPower(){let p=emptyCell([{x:doorX,y:doorY},{x:foodX,y:foodY}]);powerX=p.x+20;powerY=p.y+20;powerDX=random()<.5?-2.5:2.5;powerDY=random()<.5?-2.5:2.5;powerActive=true}
function wallHit(tx,ty){let l=floor((tx-14)/cell),r=floor((tx+14)/cell),t=floor((ty-14)/cell),b=floor((ty+14)/cell);if(l<0||r>=cols||t<0||b>=rows)return false;return grid[l][t]||grid[r][t]||grid[l][b]||grid[r][b]}
function gameOverScreen(){background(15,10,20);textAlign(CENTER,CENTER);fill(255,234,3);textSize(40);text('GAME OVER!',width/2,height/2-40);fill(0,255,200);textSize(25);text(`Final Score: ${score}`,width/2,height/2);fill(113,71,249);textSize(18);text('Press Space to restart.',width/2,height/2+40)}
function keyPressed(){if(over&&key===' '){over=false;hardness=score=0;lives=3;generateLevel()}return false}
