const mazeMap=["###############","#.#...........#","#.#.###.#####.#","#...#...#.....#","#.#.#.#.#.#.#.#","#...#.....#.#.#","#.###.#.#.###.#","#.....#...#...#","#.#######.#.###","#.#.......#...#","#.#.#.#.#####.#","#.#...#.....#.#","#.#####.#.###.#","#.......#.....#","###############"];
const CELL=50,ROWS=15,COLS=15,NUM_WOLVES=8,NUM_MONKEYS=2;
let gameState=0,dorothyX,dorothyY,direction="RIGHT",moving=false,lives=3,shoeX,shoeY,hasRubyShoes=false,shoeTimer=0,gameStartTime=0,wolves=[],monkeys=[],wolvesActive=false,monkeysActive=false,blinking=false,blinkStartTime=0,lastDamageTime=-99999;
const startX=75,startY=75,dorothySpeed=2.8,shoeInterval=5000,wolfStartTime=13000,monkeyStartTime=30000,damageCooldown=1200;
function setup(){const canvas=createCanvas(750,750);canvas.parent("canvas-host");wolves=Array.from({length:NUM_WOLVES},()=>new Wolf());monkeys=Array.from({length:NUM_MONKEYS},()=>new FlyingMonkey());}
function draw(){if(gameState===0)return drawTitle();if(gameState===1)return drawInstructions();if(gameState===2)return drawGame();if(gameState===3)return drawWin();drawGameOver();}
function screenText(title,lines,accent="#ffdc3c"){background(18,30,20);textAlign(CENTER,CENTER);fill(accent);textSize(56);text(title,width/2,120);fill(255);textSize(18);lines.forEach((line,i)=>text(line,width/2,230+i*42));}
function drawTitle(){screenText("WIZARD OF OZ",["DOROTHY'S MAZE ADVENTURE","","PRESS SPACE OR ENTER"]);}
function drawInstructions(){screenText("HOW TO PLAY",["Guide Dorothy through the maze.","Collect the moving RUBY SHOES first.","Then reach the YELLOW BRICK ROAD.","Wolves enter after 13 seconds.","Flying monkeys enter after 30 seconds.","You have 3 lives.","","ARROW KEYS TO MOVE","SPACE OR ENTER TO START"]);}
function startGame(){gameState=2;gameStartTime=millis();dorothyX=startX;dorothyY=startY;direction="RIGHT";moving=false;lives=3;hasRubyShoes=wolvesActive=monkeysActive=blinking=false;lastDamageTime=-99999;wolves.forEach(w=>w.active=false);monkeys.forEach(m=>m.active=false);placeRubyShoes();shoeTimer=millis();}
function drawGame(){drawMaze();const elapsed=millis()-gameStartTime;if(!wolvesActive&&elapsed>=wolfStartTime){wolves.forEach(w=>{spawnWolf(w);w.active=true;});wolvesActive=true;}if(!monkeysActive&&elapsed>=monkeyStartTime){monkeys[0].spawn(width-80,80);monkeys[1].spawn(80,height-80);monkeysActive=true;}if(!hasRubyShoes){drawShoes(shoeX,shoeY);if(millis()-shoeTimer>=shoeInterval){placeRubyShoes();shoeTimer=millis();}}readMovement();if(!blinking&&moving)moveDorothy();if(wolvesActive)wolves.forEach(w=>{w.update();w.display();});if(monkeysActive)monkeys.forEach(m=>{m.update();m.display();});if(!hasRubyShoes&&dist(dorothyX,dorothyY,shoeX,shoeY)<25)hasRubyShoes=true;checkGoal();updateBlinking();if(!blinking||floor((millis()-blinkStartTime)/250)%2===0)drawDorothy(dorothyX,dorothyY);drawUI();}
function isGoalCell(row,col){return row===13&&col>=9&&col<=13||col===13&&row>=12&&row<=13;}function isPathCell(row,col){return row>=0&&row<ROWS&&col>=0&&col<COLS&&mazeMap[row].charAt(col)===".";}function isWalkable(x,y){return isPathCell(floor(y/CELL),floor(x/CELL));}
function drawMaze(){background(18,45,22);for(let row=0;row<ROWS;row++)for(let col=0;col<COLS;col++){const x=col*CELL,y=row*CELL;if(isPathCell(row,col)){fill(isGoalCell(row,col)?color(245,205,35):color(190,62,52));noStroke();rect(x,y,CELL,CELL);stroke(150,45,40);strokeWeight(1);[12,25,38].forEach(offset=>line(x,y+offset,x+CELL,y+offset));}else{noStroke();fill(20,60,25);rect(x,y,CELL,CELL);fill(30,85,32);rect(x+4,y+4,CELL-8,CELL-8,7);fill(45,110,38);ellipse(x+13,y+17,15,12);ellipse(x+30,y+29,17,13);}}fill(100,65,30);rect(8,4,65,25,4);fill(255);textAlign(CENTER,CENTER);textSize(14);text("START",40,16);if(hasRubyShoes){fill(255);triangle(720,665,742,680,720,695);}}
function readMovement(){const dirs=[[LEFT_ARROW,"LEFT"],[RIGHT_ARROW,"RIGHT"],[UP_ARROW,"UP"],[DOWN_ARROW,"DOWN"]];const active=dirs.find(([code])=>keyIsDown(code));moving=!!active;if(active)direction=active[1];}
function moveDorothy(){let nx=dorothyX,ny=dorothyY;if(direction==="LEFT")nx-=dorothySpeed;if(direction==="RIGHT")nx+=dorothySpeed;if(direction==="UP")ny-=dorothySpeed;if(direction==="DOWN")ny+=dorothySpeed;if(canOccupy(nx,ny)){dorothyX=nx;dorothyY=ny;alignToPath();}else moving=false;}
function canOccupy(x,y){const r=8;return isWalkable(x,y)&&isWalkable(x-r,y)&&isWalkable(x+r,y)&&isWalkable(x,y-r)&&isWalkable(x,y+r);}function alignToPath(){const cx=floor(dorothyX/CELL)*CELL+CELL/2,cy=floor(dorothyY/CELL)*CELL+CELL/2;if((direction==="UP"||direction==="DOWN")&&abs(dorothyX-cx)<5)dorothyX=cx;if((direction==="LEFT"||direction==="RIGHT")&&abs(dorothyY-cy)<5)dorothyY=cy;}
function placeRubyShoes(){for(let i=0;i<1000;i++){const row=floor(random(1,ROWS-1)),col=floor(random(1,COLS-1)),x=col*CELL+CELL/2,y=row*CELL+CELL/2;if(isPathCell(row,col)&&!isGoalCell(row,col)&&dist(x,y,dorothyX,dorothyY)>=150){shoeX=x;shoeY=y;return;}}}
function checkGoal(){const col=floor(dorothyX/CELL),row=floor(dorothyY/CELL);if(isGoalCell(row,col)&&hasRubyShoes){gameState=3;moving=false;}}
function damage(sendHome=false){if(millis()-lastDamageTime<damageCooldown)return;lastDamageTime=millis();lives--;if(sendHome){dorothyX=startX;dorothyY=startY;}moving=false;blinking=true;blinkStartTime=millis();if(lives<=0){gameState=4;blinking=moving=false;}}
function updateBlinking(){if(blinking&&millis()-blinkStartTime>=1000)blinking=false;}
function spawnWolf(w){for(let i=0;i<1000;i++){const row=floor(random(1,ROWS-1)),col=floor(random(1,COLS-1)),x=col*CELL+CELL/2,y=row*CELL+CELL/2;if(isPathCell(row,col)&&!isGoalCell(row,col)&&dist(x,y,dorothyX,dorothyY)>=150){Object.assign(w,{x,y,row,col,active:true});w.chooseDirection();return;}}}
class Wolf{constructor(){this.x=0;this.y=0;this.row=0;this.col=0;this.moveDirection=-1;this.speed=1.5;this.active=false;}update(){if(!this.active)return;this.col=round((this.x-CELL/2)/CELL);this.row=round((this.y-CELL/2)/CELL);let tr=this.row,tc=this.col;if(this.moveDirection===0)tc++;if(this.moveDirection===1)tc--;if(this.moveDirection===2)tr--;if(this.moveDirection===3)tr++;if(!isPathCell(tr,tc)){this.chooseDirection();return;}const tx=tc*CELL+CELL/2,ty=tr*CELL+CELL/2,dx=tx-this.x,dy=ty-this.y,d=sqrt(dx*dx+dy*dy);if(d<=this.speed){this.x=tx;this.y=ty;this.row=tr;this.col=tc;this.chooseDirection();}else{this.x+=dx/d*this.speed;this.y+=dy/d*this.speed;}if(dist(this.x,this.y,dorothyX,dorothyY)<27){damage();spawnWolf(this);}}chooseDirection(){const possible=[];if(isPathCell(this.row,this.col+1))possible.push(0);if(isPathCell(this.row,this.col-1))possible.push(1);if(isPathCell(this.row-1,this.col))possible.push(2);if(isPathCell(this.row+1,this.col))possible.push(3);if(possible.length>1){const reverse=[1,0,3,2][this.moveDirection];const i=possible.indexOf(reverse);if(i>=0)possible.splice(i,1);}if(possible.length)this.moveDirection=random(possible);}display(){if(this.active)drawWolf(this.x,this.y);}}
class FlyingMonkey{constructor(){this.active=false;this.x=0;this.y=0;this.firing=false;}spawn(x,y){this.x=x;this.y=y;this.active=true;this.chooseTarget();}chooseTarget(){this.tx=random(50,width-50);this.ty=random(50,height-50);}update(){if(!this.active)return;const dx=this.tx-this.x,dy=this.ty-this.y,d=sqrt(dx*dx+dy*dy);if(d<15)this.chooseTarget();else{this.x+=dx/d*1.8;this.y+=dy/d*1.8;}this.firing=dist(this.x,this.y,dorothyX,dorothyY)<=100;if(this.firing)damage(true);}display(){if(this.firing){stroke(40,255,70);strokeWeight(5);line(this.x,this.y,dorothyX,dorothyY);}drawMonkey(this.x,this.y);}}
function drawDorothy(x,y){push();translate(x,y);noStroke();fill(80,145,220);triangle(-14,18,14,18,0,-10);fill(255,220,180);circle(0,-18,17);fill(105,65,35);arc(0,-20,20,18,PI,TWO_PI);fill(180,25,35);ellipse(-7,22,12,7);ellipse(7,22,12,7);pop();}
function drawShoes(x,y){push();translate(x,y);fill(210,20,45);noStroke();ellipse(-8,2,19,10);ellipse(8,2,19,10);fill(255,100,120);circle(-8,0,4);circle(8,0,4);pop();}
function drawWolf(x,y){push();translate(x,y);fill(105);stroke(45);triangle(-18,-8,-8,-24,0,-9);triangle(0,-9,9,-24,18,-8);ellipse(0,2,38,28);fill(255,180,30);circle(-7,0,4);circle(7,0,4);pop();}
function drawMonkey(x,y){push();translate(x,y);fill(95,55,38);stroke(40);ellipse(0,0,55,40);circle(0,-15,34);fill(205,150,105);ellipse(0,-12,22,17);fill(60);circle(-5,-15,3);circle(5,-15,3);fill(95,55,38);triangle(-16,-30,-8,-19,-22,-18);triangle(16,-30,8,-19,22,-18);pop();}
function drawUI(){fill(0,180);noStroke();rect(10,10,180,58,8);fill(255);textAlign(LEFT,CENTER);textSize(18);text(`Lives: ${lives}`,25,30);textSize(13);fill(hasRubyShoes?color(255,220,40):255);text(hasRubyShoes?"RUBY SHOES ✓":"Find the Ruby Shoes!",25,52);fill(0,150);rect(width-180,10,165,38,8);fill(255);textAlign(CENTER,CENTER);text(`Time: ${floor((millis()-gameStartTime)/1000)}s`,width-97,29);}
function drawWin(){screenText("YOU WIN!",["Dorothy reached the Yellow Brick Road!","","Press ENTER to play again"]);}function drawGameOver(){screenText("GAME OVER",["Dorothy lost all 3 lives.","","Press ENTER to try again"],"#dc2828");}
function keyPressed(){if(key===" "||keyCode===ENTER||keyCode===RETURN){if(gameState===0)gameState=1;else if(gameState===1||gameState===3||gameState===4)startGame();return false;}if([LEFT_ARROW,RIGHT_ARROW,UP_ARROW,DOWN_ARROW].includes(keyCode))return false;}function keyReleased(){if([LEFT_ARROW,RIGHT_ARROW,UP_ARROW,DOWN_ARROW].includes(keyCode))return false;}
